automations:
  - name: "automation2"
    channel_ids:
      - 1289860921744691258
      - 1398010941983162458
      - 1412115220804927628
    message: "Hello I'm RIYA!"
    #i just commited change in this file to check the workflow github action
