name: Discord Bot

on:
 push:
    branches:
      - main
 schedule:
    - cron: "06 12 * * *"   # 07:05 UTC = 12:35 IST. Change if needed. shifted the time to 24 minutes prior to tachle the delay in github scheduled automation

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      RIYA_TOKEN: ${{ secrets.RIYA_TOKEN }}   # <-- must exist in Repo Secrets
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Debug repo (optional)
        run: |
          echo "PWD:"
          pwd
          echo "Files:"
          ls -R

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run bot
        run: python bot.py
