name: Discord Bot

on:
  workflow_dispatch:    # manual trigger
  schedule:
    - cron: "5 7 * * *"   # 07:05 UTC = 12:35 IST. Change if needed.

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      RIYA_TOKEN: ${{ secrets.RIYA_TOKEN }}   # <-- must exist in Repo Secrets
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Debug repo (optional)
        run: |
          echo "PWD:"
          pwd
          echo "Files:"
          ls -R

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run bot
        run: python bot.py
